# action.yml
name: 'MAUI Android container build action'
description: 'Build MAUI Android projection inside a docker conainer'
inputs:
  SolutionPath:  # id of input
    description: 'Path to the solution file, relative to repository root'
    required: true
    default: ''
  ProjectPath:  # id of input
    description: 'Path to the Android project file, relative to repository root'
    required: true
    default: ''
  BuildConfiguration:  # id of input
    description: 'Configuration to build with'
    required: true
    default: ''
  SigningKeyAlias:  # id of input
    description: 'Alias of the key to sign with'
    required: true
    default: ''
  SigningKeyPassword:  # id of input
    description: 'Password of the key to sign with'
    required: true
    default: ''
  SigningKeyStore:  # id of input
    description: 'Keystore to sign with in Base64 format'
    required: true
    default: ''
  SigningKeystorePassword:  # id of input
    description: 'Password of the keystore to sign with'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.SolutionPath }}
    - ${{ inputs.ProjectPath }}
    - ${{ inputs.BuildConfiguration }}
    - ${{ inputs.SigningKeyAlias }}
    - ${{ inputs.SigningKeyPassword }}
    - ${{ inputs.SigningKeyStore }}
    - ${{ inputs.SigningKeystorePassword }}
